### ISSUE TITLE
browser-test target fails

### ISSUE THREAD

**Issue by bradh** [ngageoint/geopackage-js#113]
The first problem is that the browserify-istanbul dev dependency is missing. Fairly easy fix.

However, once getting past that, this is a bit more confusing:
```
bradh@ubuntu1710:~/geopackage-js$ yarn browser-test
yarn run v1.6.0
$ browserify -t browserify-istanbul ./test/test.js --standalone tests --exclude sqlite3 --exclude inquirer -o bundle/test.bundle.js -d
$ ./test/cli
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/.bin/mocha-phantomjs ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Possibly it doesn't like my VM environment, but its hard to see.

**Comment by danielbarela** [comment]
Any update on this @bradh or is this OBE?

**Comment by bradh** [comment]
I haven't done any work on it.
