### ISSUE TITLE
It is asking to download visual studio 2017 and giving exception while installation.

### ISSUE THREAD

**Issue by bjornlarssonviggeby** [ngageoint/geopackage-js#155]
I am trying to install @ngageoint/geopackage in my angular 8.2 project but after running  npm install @ngageoint/geopackage I am getting the following errors. I have node v12.16.3, Angular CLI: 9.1.0, Windows 10 and 64 bit operating system. I have installed python 3.8.3 also but it started looking for visual studio 2017 and Visual Studio C++.  I can install these dependencies on my machine but I can't install these much of dependencies on my hosting server. So is there any solution to simply install this library without these visual studio packages and all?

```
> integer@1.0.7 install D:\Office\Proj\node_modules\integer
> node-gyp rebuild


D:\Office\Proj\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config  
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.4.29709.97) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community" 
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS checking VS2017 (15.9.28307.1146) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)   
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Office\Proj\node_modules\integer
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN @angular/http@5.2.11 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@5.2.11 requires a peer of @angular/core@5.2.11 but none is installed. You must install peer dependencies yourself.        
npm WARN @angular/http@5.2.11 requires a peer of @angular/platform-browser@5.2.11 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/tsc-wrapped@4.4.6 requires a peer of typescript@^2.1.5 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/common@9.0.0 requires a peer of @angular/common@^9.0.0 but none is installed. You must install peer dependencies yourself. 
npm WARN @nguniversal/common@9.0.0 requires a peer of @angular/core@^9.0.0 but none is installed. You must install peer dependencies yourself.   
npm WARN @ngx-meta/core@7.0.0 requires a peer of @angular/core@>=7.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.npm WARN @ngx-meta/core@7.0.0 requires a peer of @angular/platform-browser@>=7.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-meta/core@7.0.0 requires a peer of @angular/platform-browser-dynamic@>=7.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-meta/core@7.0.0 requires a peer of @angular/router@>=7.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN angular-transfer-http-response@0.0.4 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-transfer-http-response@0.0.4 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-packagr@1.7.0 requires a peer of typescript@^2.3.4 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.3 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.3 requires a peer of @angular/forms@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.3 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.        
npm WARN tsickle@0.21.6 requires a peer of typescript@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\sass\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PMS\AppData\Roaming\npm-cache\_logs\2020-06-05T11_42_37_089Z-debug.log
```

**Comment by danielbarela** [comment]
I will be publishing the 3.0 baseline as non-beta this week.  Once I do that, it will use the prebuilt version of integer which should correct this.

**Comment by danielbarela** [comment]
I published the new version today.  Please try with 3.0.0.  This upgrades the integer library to a version which has prebuilt libraries for many node versions and operating systems.
