### ISSUE TITLE
unable to initialize canvas

### ISSUE THREAD

**Issue by murithigeo** [ngageoint/geopackage-js#193]
I'm running into this error:
`Error: Unable to initialize canvas.
    at Function.<anonymous> (D:\Projects\nOpenAPIexegesis\node_modules\@ngageoint\geopackage\dist\lib\api.js:139:31)
    at step (D:\Projects\nOpenAPIexegesis\node_modules\@ngageoint\geopackage\dist\lib\api.js:33:23)
    at Object.throw (D:\Projects\nOpenAPIexegesis\node_modules\@ngageoint\geopackage\dist\lib\api.js:14:53)
    at rejected (D:\Projects\nOpenAPIexegesis\node_modules\@ngageoint\geopackage\dist\lib\api.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
D:\Projects\nOpenAPIexegesis\node_modules\@ngageoint\geopackage\dist\canvaskit\canvaskit.js:1504
                throw a; }), process.on("unhandledRejection", Na), ta = function (a) { process.exit(a); }, t.inspect =
                ^

RuntimeError: abort(Error: Unable to initialize canvas.). Build with -s ASSERTIONS=1 for more info.
    at process.Na (D:\Projects\nOpenAPIexegesis\node_modules\@ngageoint\geopackage\dist\canvaskit\canvaskit.js:1635:47)
    at process.emit (node:events:514:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v18.17.0`.
OS: Windows 10

**Comment by tobilg** [comment]
We get the same error when using Node 18...

**Comment by murithigeo** [comment]
Well this sucks considering that the other option for geojson to GPKG converter is a wrapper and can't handle large file sizes
